import { supabase } from './supabaseClient';
import { BluntMessage, BluntReply } from '../types';

// Map DB (snake_case) to Client (camelCase)
const mapFromDB = (row: any): BluntMessage => ({
  id: row.id,
  content: row.content,
  isAnonymous: row.is_anonymous,
  allowReply: row.allow_reply,
  createdAt: Number(row.created_at),
  acknowledged: row.acknowledged,
  denied: row.denied,
  recipientName: row.recipient_name,
  recipientNumber: row.recipient_number,
  deliveryMode: row.delivery_mode as any,
  scheduledFor: Number(row.scheduled_for),
  attachment: row.attachment,
  attachmentType: row.attachment_type as any,
  attachmentName: row.attachment_name,
  postToFeed: row.post_to_feed,
  replies: (row.replies || []).map((r: any) => ({
    id: r.id,
    content: r.content,
    createdAt: Number(r.created_at)
  }))
});

// Map Client to DB
const mapToDB = (msg: BluntMessage, userId: string): any => ({
  // id generated by DB or passed if UUID
  user_id: userId,
  content: msg.content,
  is_anonymous: msg.isAnonymous,
  allow_reply: msg.allowReply,
  created_at: msg.createdAt,
  acknowledged: msg.acknowledged,
  denied: msg.denied || false,
  recipient_name: msg.recipientName,
  recipient_number: msg.recipientNumber,
  delivery_mode: msg.deliveryMode,
  scheduled_for: msg.scheduledFor,
  attachment: msg.attachment,
  attachment_type: msg.attachmentType,
  attachment_name: msg.attachmentName,
  post_to_feed: msg.postToFeed || false
});

export const saveBlunt = async (blunt: BluntMessage): Promise<void> => {
  const { data: { user } } = await supabase.auth.getUser();

  // SUPPORT GUEST POSTING
  // If no user is logged in, we try to use the guest ID from the blunt message or a generated one.
  // Note: RLS policies on Supabase must allow INSERTs where user_id is null or match a guest rule.
  const userId = user ? user.id : (blunt.isAnonymous ? 'guest-user' : null);

  // If we really want to enforce a real user for guests (e.g. anonymous auth), 
  // we would initiate that here, but for now we'll try to insert with what we have.

  const dbPayload = mapToDB(blunt, userId || 'anon');

  // If we are guest, we might need to remove user_id if the DB treats it as a foreign key that must exist.
  // If the DB has `user_id uuid references auth.users(id)`, inserting a random string will fail FK constraint.
  // We will attempt to insert NULL for user_id if it's a guest, assuming the column is nullable.
  if (!user) {
    delete dbPayload.user_id;
  }

  const { error } = await supabase.from('blunts').insert({
    ...dbPayload,
    id: blunt.id
  });

  if (error) {
    if (error.code === '23503') { // Foreign key violation
      throw new Error("Guest posting is currently disabled by server policy (Foreign Key). Please sign in.");
    }
    if (error.code === '42501') { // RLS violation
      throw new Error("Guest posting is currently disabled by server policy (RLS). Please sign in.");
    }
    throw error;
  }
};

export const getBlunt = async (id: string): Promise<BluntMessage | null> => {
  const { data, error } = await supabase
    .from('blunts')
    .select('*, replies(*)')
    .eq('id', id)
    .single();

  if (error || !data) return null;
  return mapFromDB(data);
};

export const updateBlunt = async (id: string, updates: Partial<BluntMessage>): Promise<void> => {
  // We only support partial updates for specific fields usually, but here's a generic one
  const payload: any = {};
  if (updates.acknowledged !== undefined) payload.acknowledged = updates.acknowledged;
  if (updates.denied !== undefined) payload.denied = updates.denied;

  const { error } = await supabase.from('blunts').update(payload).eq('id', id);
  if (error) throw error;
};

export const addReply = async (bluntId: string, replyContent: string): Promise<BluntMessage | null> => {
  const { error } = await supabase.from('replies').insert({
    blunt_id: bluntId,
    content: replyContent,
    created_at: Date.now()
  });
  if (error) throw error;
  return getBlunt(bluntId);
};

export const acknowledgeBlunt = async (id: string): Promise<void> => {
  await updateBlunt(id, { acknowledged: true });
};

export const denyBlunt = async (id: string): Promise<void> => {
  await updateBlunt(id, { denied: true });
};

export const getStoredBlunts = async (): Promise<BluntMessage[]> => {
  // Supabase RLS ensures we only see our own
  const { data, error } = await supabase
    .from('blunts')
    .select('*, replies(*)')
    .order('created_at', { ascending: false });

  if (error) throw error;
  return (data || []).map(mapFromDB);
};

export const getPublicBlunts = async (): Promise<BluntMessage[]> => {
  const { data, error } = await supabase
    .from('blunts')
    .select('*, replies(*)')
    .eq('post_to_feed', true)
    .order('created_at', { ascending: false });

  if (error) throw error;
  return (data || []).map(mapFromDB);
};
